name: CI

on:
  pull_request:
    branches: ["*"]

jobs:
  lint-and-test:
    runs-on: ubuntu-24.04

    permissions:
      pull-requests: write

    steps:
      - uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v7
        with:
          version: "0.9.26"

      - name: Run ruff lint
        run: uv run ruff format --check

      - name: Run ruff lint
        run: uv run ruff check 

      - name: Run ty check
        run: uv run ty check

      - name: Run tests
        run: uv run pytest -v

      - name: Login to docker.io for buildx access
        uses: docker/login-action@v3
        with:
          username: portswigger
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}

      - name: Login to dhi.io for buildx access
        uses: docker/login-action@v3
        with:
          username: portswigger
          password: ${{ secrets.DOCKER_PUSH_TOKEN }}
          registry: dhi.io

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          driver: cloud
          endpoint: portswigger/shared-platform

      - name: Build and push
        uses: docker/build-push-action@v6
        with:
          tags: portswigger/noa-scout-test:pr-latest
          outputs: type=registry
          provenance: true
          sbom: true
          push: true
          load: true
          attests: type=provenance,mode=max

      - name: Docker Scout
        uses: docker/scout-action@v1
        with:
          command: cves
          image: portswigger/noa-scout-test:pr-latest
